### ISSUE TITLE
可不可以分享下 Atom 的插件与配置呀

### ISSUE THREAD

**Issue by lqzhgood** [levblanc/vue-2-basics#1]
视频中看到 LZ 的 IDE 挺好看的。 想转成 ATOM，可以分享下插件与配置嘛？

大概看了下用 https://atom.io/packages/sync-settings 可以直接导出

**Comment by levblanc** [comment]
之前因为装了Nuclide之后感觉总是有冲突，所以把整个Atom刷了一回。

目前的配置已经跟视频里面的不一样了。sync-settings的我弄成了私人的gist。

这里弄了一个公开的：[atom settings as of 2017/06/26](https://gist.github.com/levblanc/a5b8b7cc1d6d2b87c5468ca2f772f91c)。
主要的都有了，sync-settings里面同步的其它配置文件我都是没改过的。

视频里面的UI theme没记错的话应该是Material Theme UI，primary color选Amber。

字体是Input，需要自行在电脑上安装，搜一下都有的。

插件什么的，就见仁见智吧。
Nuclide一来会装一堆，用着用着觉得有需要也会装一堆，
以至于我都不记得自己装过什么了。
